/**:
  ros__parameters:
    grasp_offsets:
      psm1:
        grip:
          up:
            position:
              x: 0.0
              y: 0.0
              z: 0.0
            orientation:
              roll: 3.141592653589793
              pitch: 0.0
              yaw: 0.0
          down:
            position:
              x: 0.0
              y: 0.0
              z: 0.0
            orientation:
              roll: 3.141592653589793
              pitch: 0.0
              yaw: 0.0
        tip:
          up:
            position:
              x: 0.0055
              y: 0.0055
              z: 0.007
            orientation:
              roll: 3.141592653589793
              pitch: 0.3
              yaw: -0.5
          down:
            position:
              x: 0.0055
              y: 0.005
              z: 0.007
            orientation:
              roll: 3.141592653589793
              pitch: 0.3
              yaw: -0.5
      psm2:
        grip:
          up:
            position:
              x: -0.009
              y: 0.003
              z: 0.008
            orientation:
              roll: 3.141592653589793
              pitch: 0.0
              yaw: 1.5
          down:
            position:
              x: -0.009
              y: 0.003
              z: -0.008
            orientation:
              roll: 0.0
              pitch: 0.0
              yaw: 1.5707963267948966
        tip:
          up:
            position:
              x: 0.0
              y: 0.0
              z: 0.0
            orientation:
              roll: -1.5707963267948966
              pitch: 0.0
              yaw: 0.0
          down:
            position:
              x: 0.0
              y: 0.0
              z: 0.0
            orientation:
              roll: -1.5707963267948966
              pitch: 0.0
              yaw: 0.0